// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputTask struct {
	TaskName    string  `json:"taskName"`
	Link        *string `json:"link"`
	Description *string `json:"description"`
}

type InputTaskState struct {
	Progress     int     `json:"progress"`
	TaskID       *string `json:"taskId"`
	TaskName     string  `json:"taskName"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	TaskFlagID   string  `json:"taskFlagId"`
	TaskFlagName string  `json:"taskFlagName"`
}

type InputTeam struct {
	TeanName string   `json:"teanName"`
	TeamMemo *string  `json:"teamMemo"`
	Users    []string `json:"users"`
}

type InputUser struct {
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Task struct {
	TaskID      *string `json:"taskId"`
	TaskName    string  `json:"taskName"`
	Link        *string `json:"link"`
	Description *string `json:"description"`
}

type TaskFlag struct {
	TaskFlagID   string `json:"taskFlagId"`
	TaskFlagName string `json:"taskFlagName"`
}

type TaskState struct {
	Task     *Task     `json:"task"`
	TaskFlag *TaskFlag `json:"taskFlag"`
	Progress int       `json:"progress"`
}

type Team struct {
	TeamID   string   `json:"teamId"`
	TeamName string   `json:"teamName"`
	TeamMemo *string  `json:"teamMemo"`
	Users    []string `json:"users"`
}

type UpdateTask struct {
	TaskID      *string `json:"taskId"`
	TaskName    string  `json:"taskName"`
	Link        *string `json:"link"`
	Description *string `json:"description"`
}

type UpdateTaskState struct {
	TaskStateID  *string `json:"taskStateId"`
	Progress     int     `json:"progress"`
	TaskID       *string `json:"taskId"`
	TaskName     string  `json:"taskName"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	TaskFlagID   string  `json:"taskFlagId"`
	TaskFlagName string  `json:"taskFlagName"`
}

type UpdateTeam struct {
	TeamID   string   `json:"teamId"`
	TeamName string   `json:"teamName"`
	TeamMemo *string  `json:"teamMemo"`
	Users    []string `json:"users"`
}

type UpdateUser struct {
	UserID   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

type User struct {
	UserID   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	RoleID   string `json:"roleId"`
}
