dev:
	go run main.go

mig-help:
	sql-migrate --help

mig-new:
	sql-migrate new ${file}

mig-up:
	sql-migrate up

mig-down:
	sql-migrate down

gqlgen-init:
	go run github.com/99designs/gqlgen init


gqlgen:
	go run github.com/99designs/gqlgen generate
